# parameters used across the pipeline

data_ingestion:
  asset: "BTC-USD"
  start_date: "2017-01-01"
  end_date: "2025-01-01"

data_preprocessing:
  train_size: 0.8

model_training:
  window_size: 100
  transaction_cost: 0.001
  initial_balance: 1.0
  reward_scaling: 1.0
  turnover_penalty: 0.0005
  net_arch: [256, 256]
  initial_lr: 0.0003
  n_steps: 4096
  batch_size: 128
  n_epochs: 15
  gamma: 0.999
  ent_coef: 0.01
  eval_freq: 5000
  total_timesteps: 5_000_000