# parameters used across the pipeline

data_ingestion:
  asset: "BTC-USD"
  start_date: "2017-01-01"
  end_date: "2025-01-01"

data_preprocessing:
  train_size: 0.8
  sma_short_window: 20
  sma_long_window: 50
  volatility_window: 20
  volume_window: 20

model_training:
  window_size: 100
  transaction_cost: 0.001
  initial_balance: 1.0
  reward_scaling: 1.0
  turnover_penalty: 0.005
  net_arch: [256, 256, 128]
  initial_lr: 0.0001
  n_steps: 2048
  batch_size: 64
  n_epochs: 15
  gamma: 0.995
  ent_coef: 0.01
  eval_freq: 5000
  total_timesteps: 1_00_000